/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        student: {
          'bg-primary': 'var(--student-bg-primary)',
          'bg-secondary': 'var(--student-bg-secondary)',
          'bg-tertiary': 'var(--student-bg-tertiary)',
          'bg-elevated': 'var(--student-bg-elevated)',
          'text-primary': 'var(--student-text-primary)',
          'text-secondary': 'var(--student-text-secondary)',
          'text-tertiary': 'var(--student-text-tertiary)',
          'text-disabled': 'var(--student-text-disabled)',
          'answer-yes': 'var(--student-answer-yes)',
          'answer-no': 'var(--student-answer-no)',
          'answer-unknown': 'var(--student-answer-unknown)',
          'semantic-error': 'var(--student-semantic-error)',
          'semantic-info': 'var(--student-semantic-info)',
          'semantic-gray': 'var(--student-semantic-gray)',
          'border-primary': 'var(--student-border-primary)',
          'border-secondary': 'var(--student-border-secondary)',
        },
        admin: {
          'bg-primary': 'var(--admin-bg-primary)',
          'bg-secondary': 'var(--admin-bg-secondary)',
          'bg-tertiary': 'var(--admin-bg-tertiary)',
          'bg-elevated': 'var(--admin-bg-elevated)',
          'text-primary': 'var(--admin-text-primary)',
          'text-secondary': 'var(--admin-text-secondary)',
          'text-tertiary': 'var(--admin-text-tertiary)',
          'text-disabled': 'var(--admin-text-disabled)',
          'semantic-error': 'var(--admin-semantic-error)',
          'semantic-success': 'var(--admin-semantic-success)',
          'semantic-warning': 'var(--admin-semantic-warning)',
          'semantic-info': 'var(--admin-semantic-info)',
          'accent-primary': 'var(--admin-accent-primary)',
          'accent-secondary': 'var(--admin-accent-secondary)',
          'border-primary': 'var(--admin-border-primary)',
          'border-secondary': 'var(--admin-border-secondary)',
        },
      },
      fontFamily: {
        heading: ['var(--font-heading)', 'serif'],
        body: ['var(--font-body)', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
      },
      spacing: {
        'grid-1': '8px',
        'grid-2': '16px',
        'grid-3': '24px',
        'grid-4': '32px',
        'grid-6': '48px',
        'grid-8': '64px',
        'grid-12': '96px',
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '300ms',
        slow: '500ms',
      },
      transitionTimingFunction: {
        'ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
        'ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
      },
    },
  },
  plugins: [],
}
