/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'student': {
          'bg-primary': '#000000',
          'bg-secondary': '#0d0d0d',
          'bg-tertiary': '#1a1a1a',
          'bg-elevated': '#262626',
          'text-primary': '#f0f0f0',
          'text-secondary': '#c8c8c8',
          'text-tertiary': '#888888',
          'text-disabled': '#555555',
          'accent-red': '#b71c1c',
          'accent-blue': '#1565c0',
          'accent-gray': '#505050',
          'border-primary': '#2a2a2a',
          'border-secondary': '#1a1a1a',
        },
        'admin': {
          'bg-primary': '#ffffff',
          'bg-secondary': '#f5f5f5',
          'bg-tertiary': '#e0e0e0',
          'bg-elevated': '#ffffff',
          'text-primary': '#000000',
          'text-secondary': '#424242',
          'text-tertiary': '#757575',
          'text-disabled': '#bdbdbd',
          'semantic-error': '#d32f2f',
          'semantic-success': '#388e3c',
          'semantic-warning': '#f57c00',
          'semantic-info': '#1976d2',
          'accent-primary': '#1976d2',
          'accent-secondary': '#424242',
          'border-primary': '#e0e0e0',
          'border-secondary': '#bdbdbd',
        },
      },
      fontFamily: {
        'heading': ['"Noto Serif JP"', '游明朝', 'serif'],
        'body': ['"Noto Sans JP"', '游ゴシック', 'sans-serif'],
        'mono': ['"Courier New"', 'Monaco', 'monospace'],
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '16px',
        '4': '24px',
        '5': '32px',
        '6': '48px',
        '7': '64px',
        '8': '96px',
      },
      borderRadius: {
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '20px',
      },
      transitionDuration: {
        'fast': '150ms',
        'normal': '300ms',
        'slow': '500ms',
      },
      transitionTimingFunction: {
        'ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
        'ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
      },
    },
  },
  plugins: [],
}
